dist: trusty

sudo: false

language: java
cache:
  directories:
    - $HOME/.m2
# Get latest install-jdk.sh script
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - openjdk11
  - openjdk12


matrix:
  include:
    - jdk: openjdk10
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

script:
  - java -version
  - mvn clean install 
